sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: osx
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

node_js:
  - 8

cache:
  directories:
    - node_modules

install:
  - nvm install 8
  - npm install electron-builder -g
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
  - export CERTIFICATE_P12=Certificate.p12
  - echo $CERTIFICATE_OSX_P12 | base64 --decode > $CERTIFICATE_P12
  - export KEYCHAIN=build.keychain
  - security create-keychain -p mysecretpassword $KEYCHAIN
  - security default-keychain -s $KEYCHAIN
  - security unlock-keychain -p mysecretpassword $KEYCHAIN
  - security set-keychain-settings -t 3600 -u $KEYCHAIN
  - security import $CERTIFICATE_P12 -k $KEYCHAIN -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign
  - "security set-key-partition-list -S apple-tool:,apple: -s -k mysecretpassword $KEYCHAIN"

script:
  - electron-builder

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: 'releases/*.*'
  skip_cleanup: true
  on:
    tags: true